version: '3.9'

services:
  spring:
    image: a3ts/spring-boot-mongo:v1
    networks:
      - front
      - db
    environment:
      - MONGO_DB_HOSTNAME=mongodb
      - MONGO_DB_USERNAME=/run/secrets/MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=/run/secrets/MONGO_DB_PASSWORD
    secrets:
      - MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD    
    ports:
      - "8080:8080"    
    restart: always
  mongodb:
    image: mongo
    networks:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=/run/secrets/MONGO_DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=/run/secrets/MONGO_DB_PASSWORD
    secrets:
      - MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD    
    volumes:
      - storage:/data/db    
    restart: always
secrets:
  MONGO_DB_USERNAME:
    file: /my_app/secrets/mongodb-secrets.txt
  MONGO_DB_PASSWORD:
    file: /my_app/secrets/mongodb-secrets.txt        

networks:
  front:
    external: true
  db:
    external: true

volumes:
  storage:
    external: true

